services:
  lifeforce:
    container_name: lifeforce
    restart: unless-stopped
    image: repka-lifeforce:latest
    ports:
      - "16001:16001"
    volumes:
      - ".env:/app/lifeforce/.env"
      - "./data/:/app/lifeforce/data/"
