services:
  lifeforce:
    container_name: lifeforce
    restart: unless-stopped
    image: repka-lifeforce:latest
    ports:
      - "16001:16001"
    volumes:
      - ".env:/app/lifeforce/.env:ro"
      - "./data/media/:/app/lifeforce/data/media:ro"
      - "./data/lifeforce.sqlite:/app/lifeforce/data/lifeforce.sqlite"
    networks:
      - lifeforce_network
networks:
  lifeforce_network:
    driver: bridge
